/**
 * Enum representing ISO 639-1 language codes.
 * @enum {string}
 */
export enum ISO639_1 {
	/** Afrikaans */
	Af = 'af',
	/** Arabic */
	Ar = 'ar',
	/** Bulgarian */
	Bg = 'bg',
	/** Bengali */
	Bn = 'bn',
	/** Czech */
	Cs = 'cs',
	/** Danish */
	Da = 'da',
	/** German */
	De = 'de',
	/** Greek */
	El = 'el',
	/** English */
	En = 'en',
	/** Spanish */
	Es = 'es',
	/** Estonian */
	Et = 'et',
	/** Persian */
	Fa = 'fa',
	/** Finnish */
	Fi = 'fi',
	/** French */
	Fr = 'fr',
	/** Hebrew */
	He = 'he',
	/** Hindi */
	Hi = 'hi',
	/** Croatian */
	Hr = 'hr',
	/** Hungarian */
	Hu = 'hu',
	/** Indonesian */
	Id = 'id',
	/** Italian */
	It = 'it',
	/** Japanese */
	Ja = 'ja',
	/** Korean */
	Ko = 'ko',
	/** Lithuanian */
	Lt = 'lt',
	/** Latvian */
	Lv = 'lv',
	/** Dutch */
	Nl = 'nl',
	/** Norwegian */
	No = 'no',
	/** Polish */
	Pl = 'pl',
	/** Portuguese */
	Pt = 'pt',
	/** Romanian */
	Ro = 'ro',
	/** Russian */
	Ru = 'ru',
	/** Slovak */
	Sk = 'sk',
	/** Slovenian */
	Sl = 'sl',
	/** Serbian */
	Sr = 'sr',
	/** Swedish */
	Sv = 'sv',
	/** Thai */
	Th = 'th',
	/** Turkish */
	Tr = 'tr',
	/** Ukrainian */
	Uk = 'uk',
	/** Vietnamese */
	Vi = 'vi',
	/** Chinese */
	Zh = 'zh'
}
